### ISSUE TITLE
Dividere la classe Carta.java in 2 classe

### ISSUE THREAD

**Issue by Ivaskuu** [Ivaskuu/battle_royale#27]
Una per la partita con tutti gli atributti e un'altra per la collezione carte.

**Comment by Artyom1608** [comment]
Per ché?

**Comment by Ivaskuu** [comment]
@Artyom1608 perché le carte collezionabile del gioco sono diverse da quelle che giochi durante la partita. Quelle durante la partita hanno:
- HP attuale
- Attacco attuale
- Se ha giocato quel turno
- ... e tanti altri attributi che mi servono.

Però aggiungere questi attributi nella classe collezione carte sarebbe sbagliato, o per lo meno, non degno di un lavoro di professionista.
